export * from './Home';
export * from './RegisterRoleDataNextLoginView';
export * from './verification/VerificationUsersView';
export * from './UsersView';
export * from './crud/CrudUsersView';
export * from './registerLotFishs/RegisterLotDataView';
export * from './registerLotFishs/EditFishLotView';
export * from './crud/CrudFishLotView';
export * from './evaluation/EvaluationDataBasicView';
export * from './evaluation/EvaluationDataView';
export * from './evaluation/EditEvaluationView';
//export { default as SettingsView } from './settings/SettingsView';
